// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
import { createTextarea, renderWith } from "obix-core-component";
export { createTextarea } from "obix-core-component";
export type { ResizeMode, TextareaConfig, TextareaState, ValidationState } from "obix-core-component";
export const renderTextarea = renderWith(createTextarea);
